### PR TITLE
Change layout of map literal(vertical editor)

### PR DESCRIPTION
**Pull request by alexanderpann**
Original request: 
_Can the list of KeyValuePairs in the MapLiteral editor be changed from identical to VerticalGrid? A map is usually useful with many elements - and there the current editor with a line or non-flush vertical termination just does not look nice._

I changed the indent layout to look like a vertical layout. I didn't like the original request because the separators would all be on a separate lines which doesn't look good. @lhartl what do you think of this change in general?

### CODE REVIEW

**Comment by lhartl** [comment]
Tbh, I don't like the new implementation. For me, it puts every key-value pair on a new line. I made a before/ after comparison. Based on that, I can not understand the request you got, because there are sufficient line breaks for me: 

Before(old implementation) 
Screenshot 2021-12-22 at 11 43 21

After (new implementation that comes with this PR): 
Screenshot 2021-12-22 at 11 42 23

**Comment by alexanderpann** [comment]
@lhartl I think I misunderstood the request. I am guessing it is about the alignment when the key value pairs are not the same length, which you can't see in your example:
```
(100 -> 2 ,  2 -> 3,
 1   -> 2 ,  3 -> 4,
 3   -> 40,  1 -> 10)
```

I don't see an easy way to achieve this in a non hacky way.

**Comment by coolya** [comment]
We could us a similar logic as for nested binary expressions. Where we switch to vertical layout when one expression is very long. Might be possible to do something similar here but not sure if it really satisfies the original request.

**Comment by alexanderpann** [comment]
Closing because a different solution was found where a change to the platform is not needed.

**Pull request closed without merging**
