### PR TITLE
[breaking] Extract shared runtime from base runtime to reduce runtime dependencies

### PR DESCRIPTION
**Pull request by sergej-koscejev**
Terms used:
* _base runtime_: solution `org.iets3.core.expr.base.runtime`
* _shared runtime_: solution `org.iets3.core.expr.base.shared.runtime`

The new shared runtime contains classes that will be used both from the generated code and by the interpreter or in-MPS code.

Even though the individual classes used by the generated code do not depend on MPS-specific classes, extracting them from the base runtime means that the generated code no longer needs to depend on a module that contain MPS-specific code (e.g. NixSupport with its usage of the node<> type).

The base runtime was taken out of module dependencies of other runtimes.

Breaking change: class INixValue was moved from the base runtime to the shared one so references to it will need to be updated (Ctrl+R to import org.iets3.core.expr.base.shared.runtime model, then F5 to update
the reference).

Another potentially breaking change is that the generated code now uses the shared runtime and its classes instead of the base runtime (e.g. SharedMinMaxHelper rather than MinMaxHelper). After it is regenerated, it will need the shared runtime JAR to execute (and should no longer need the base runtime JAR).

### CODE REVIEW

**Review by wsafonov — APPROVED** [review]
LGTM, we would just need to communicate the breaking change properly to the customer projects.

**Comment by sergej-koscejev** [comment]
> LGTM, we would just need to communicate the breaking change properly to the customer projects.

Who is "we" and what exactly is "properly"?

**Comment by wsafonov** [comment]
> Who is "we" and what exactly is "properly"?

Those in itemis who are involved in projects using iets3.os. But we would anyway soon have a proper change log with release notes which would simplify this task.

**Comment by sergej-koscejev** [comment]
@wsafonov I want to merge this PR this week. Do you want me to increase some version number somewhere or can I just go ahead and merge?

**Comment by wsafonov** [comment]
@sergej-koscejev we don't apply any semantic versioning (yet), so it's only important that we can clearly track all changes in PRs between the specific builds. If @lhartl is also ok with the breaking changes so far, you can just go ahead and merge.

**Comment by lhartl** [comment]
Looks good to me. 
For communication: I already posted a heads up in the KernelF channel when I noticed this PR first.

**Review by lhartl — APPROVED** [review]

**Comment by wsafonov** [comment]
@sergej-koscejev is it still blocked by anything or can we merge it soon?

**Comment by sergej-koscejev** [comment]
@wsafonov you can merge it, I just haven't had time to do it myself yet.

**Pull request merged**
