### PR TITLE
[breaking?] Publish KernelF runtime + remove MPS dependency from published artifacts

### PR DESCRIPTION
**Pull request by sergej-koscejev**
KernelF runtimes are published as separate artifacts, with dependencies.

Also contains changes described in #491 (removed MPS dependency from published artifacts), which could be potentially breaking, therefore we mark this PR also as breaking.

### CODE REVIEW

**Comment by sergej-koscejev** [comment]
This contains #466, merge that before this one.

**Comment by sergej-koscejev** [comment]
The list of runtime modules that are combined does not include `*.genjava.rt` because it's not clear whether it should or not. Comments?

**Comment by wsafonov** [comment]
Could you add some comments on the rationale for combining several jars into one artifact? Is it just convenience of not having to provide 4 jars on the classpath?

**Comment by sergej-koscejev** [comment]
> Could you add some comments on the rationale for combining several jars into one artifact? Is it just convenience of not having to provide 4 jars on the classpath?

Yes, that's the main reason. I'm not sure myself if it's a good enough reason.

**Comment by wsafonov** [comment]
> Yes, that's the main reason. I'm not sure myself whether it's a good enough reason.

That exactly what I'm asking myself. In case we would have numerous (>5) runtimes that we would want to use frequently in multiple scenarios, then yes, it would make perfect sense. Right now though the only scenario is for external generation. And creating a special publication for that feels a bit too much. Rather I would expect that such kind of automation would be created on the consumer side.

But if you say there is no optimal way to do it elsewhere and it would save you a lot of time and make things really easy, well let's just consider that as good enough reason for now.

> The list of runtime modules that are combined does not include *.genjava.rt because it's not clear whether it should or not. Comments?

If that runtime is only used in the generation, I would keep it like that. But anyway, right now you are the only consumer of the new combined runtime artifact, so you can decide, if you need it there or not.

**Comment by sergej-koscejev** [comment]
Also note that I adjusted the dependencies of other artifacts here, like in #491.

**Review by wsafonov — APPROVED** [review]
LGTM now, thanks for cleaning up!

**Pull request merged**
