### PR TITLE
Fix/pcollections refernces

### PR DESCRIPTION
**Pull request by heikob2**
- removed broken model-dependencies on old pcollections.jar for: 
  - org.iets3.core.expr.collections.interpreter.plugin

- Removed not existing solution from project-paths: solutions/org.iets3.core.expr.base.collection.stubs

CI: https://build.mbeddr.com/viewType.html?buildTypeId=Iets3_BuildOrgIets3core&branch_Iets3_Iets3OpenSource=fix%2Fpcollections-refernces&tab=buildTypeStatusDiv

### CODE REVIEW

**Comment by arimer** [comment]
I am not sure what you are doing, but it looks wrong. 
solutions/org.iets3.core.expr.base.collection.stubs
Was created by me and without it master would not build..

**Comment by heikob2** [comment]
Hi Alexander, you created "collections.stubs", but there was also "collection.stub" contained in the project-paths.

**Comment by arimer** [comment]
Commits: 07f8c5f6, e592164e looks ok for me. 

But why did you add a dep. from `org.iets3.core.expr.messages.plugin` to `org.iets3.core.expr.base.collections.stubs` to in commit 8b0a2297? It is not used at all.

**Comment by heikob2** [comment]
Yes, you are right. I will remove the dependency dep. from `org.iets3.core.expr.messages.plugin` to `org.iets3.core.expr.base.collections.stubs`.

**Comment by arimer** [comment]
LGTM

**Comment by heikob2** [comment]
thank you arimer :)

**Pull request merged**
