### PR TITLE
implement enum equality comparison

### PR DESCRIPTION
**Pull request by alexanderpann**
- The _equals_ method was missing for _EnumLiteral_.
- fixes https://github.com/IETS3/iets3.opensource/issues/886

### CODE REVIEW

**Review by arimer — COMMENTED** [review]
In genal it looks fine. 

Some minor questions:

1. why do you delegate to the [super.equals()](http://127.0.0.1:63320/node?ref=r%3A93cd1fe8-b296-405c-a6e6-040c940ccfa1%28org.iets3.core.expr.toplevel.plugin%29%2F6127542811960197981) instead of returning "false"?
2. what is this [default concrete concept](http://127.0.0.1:63320/node?ref=r%3A17e537dd-82d4-485e-a86b-bac87852274c%28org.iets3.core.expr.tests.constraints%29%2F4196960000451511183) doing? Will it create a concerete concept, where an abstract concept would be created elsewise?
3. Why are you delegating to [EqualsHelper.equals()](http://127.0.0.1:63320/node?ref=r%3A7961970e-5737-42e2-b144-9bef3ad8d077%28org.iets3.core.expr.tests.behavior%29%2F6127542811960532028) here although we have no special case handling of EnumLiteral inside the EqualsHelper?
4. Maybe you know why In geneneral, EqualsHelper is performing additional checks (like for RecordValue) instead of moving that logic to the `equals()` method of RecordValue?

**Comment by alexanderpann** [comment]
1.  I don't know if it makes a difference but I only wanted to overwrite the comparison logic for enum literals and nothing else.
2.  Yes.
3.  Yes, that is correct but we always use this class for comparison. I changed it to prevent future bugs.
4.  The changes in EqualsHelper were merged from a class called `ComparisonHelper` but I agree that the logic could be moved to the class RecordValue itself and checked by it is not the same implementation.

**Review by psuzzi — APPROVED** [review]
The PR adds the comparison logic for enum literals, and add tests. 

Based on prior review comments and answers, the PR looks good to me. 

As noted in the review, I agree it would make sense returning false in [EnumLiteral#equals()](http://127.0.0.1:63320/node?ref=r%3A93cd1fe8-b296-405c-a6e6-040c940ccfa1%28org.iets3.core.expr.toplevel.plugin%29%2F6127542811960197972) instead of using equals, but this does not prevent the approval..

**Review by psuzzi — APPROVED** [review]
LGTM

**Pull request merged**
