### PR TITLE
Add editor hint support for trace 

### LINKED ISSUE #974: Add missing editor hint for conditinal editors of trance
Having dedicated editor hints which are used in conditional editors trageting tracing might improve overall runtime performance.

### PR DESCRIPTION
**Pull request by arimer**
Fixes #974

### CODE REVIEW

**Review by alexanderpann — CHANGES_REQUESTED** [review]
Did you mean `!isTraceHintAvailable()` in the is applicable block? Otherwise, you set the hint only when it is already set.

**Comment by arimer** [comment]
Might, be. Let me check.

**Comment by arimer** [comment]
Now you made me think if we do even want to check in the editor hint in the precondition of the action. I don't think we want to deactive the action if the hint is already set. 🤔

**Comment by mgronover** [comment]
I found the following points:

1. The menu entries "show trace" and "stop trace" causes an influence on user settings in editor hints.

2. I would suggest that we do not need a second point to activate/deactivate the trace explorer "show trace"/"stop trace". The Toolbar of the TraceExplorer can be used to hide the decorated code:
image

I totally agree with the editor hint for the Tracing Editor. The reason is explained here: https://github.com/IETS3/iets3.opensource/pull/1005

So I would prefer using the approach of https://github.com/IETS3/iets3.opensource/pull/1005.

**Comment by arimer** [comment]
drop in favor of #1005

**Pull request closed without merging**
