### PR TITLE
Minor coverage fixes

### PR DESCRIPTION
**Pull request by alexanderpann**
- fixes empty cells in IMultiDecTab
- fixes lambda expression
- fixes short lambda expression
- ignores documentation comments

### CODE REVIEW

**Review by lhartl — DISMISSED** [review]
looks good to me

**Review by wsafonov — CHANGES_REQUESTED** [review]
For both kinds of lambda expressions, `LambdaExpression` and `ShortLambdaExpression`, I don't think simply adding all descendants to the coverage is the right approach. One can think of conditional parts inside the lambda expression which would not be executed but still will be reported as covered. This is not correct in my opinion.

**Comment by alexanderpann** [comment]
@wsafonov test cover function:
```
fun filterList(liste: list<struktur>) = liste.where(|outer: struktur => outer.wert > 0 
&& liste.map(|value: struktur => value.wert + outer.wert|).isNotEmpty 
&& liste.map(|it.wert + outer.wert + liste.map(|it.wert|).sum + if liste.isEmpty then 1 else 0|).isNotEmpty|)
```
It is called with a non-empty list and the coverage shows that the last 0 expression can never be reached and everything else is covered as it should be.  Let me know if you think I missed a test case.

**Comment by wsafonov** [comment]
@alexanderpann regarding your test, one can of course imagine some more complex cases with conditional execution, but as far the basic stuff works, this should be ok for us.

I just have one question regarding the new code in `LambdaValue`:
```java
node<> originalNode = mapping.keys.findFirst({~key => mapping[key] == it; }); 
if (DefaultCoverageAnalyzer.hasNodeCoverage(it)) { 
   coverage.coverValue(originalNode, null); 
}
``` 
Shouldn't `isNodeCovered` be used here instead? Exactly same as in the code before.

**Review by wsafonov — DISMISSED** [review]

**Comment by wsafonov** [comment]
@alexanderpann can you resolve the conflicts? I'll merge then right thereafter

**Review by wsafonov — APPROVED** [review]

**Pull request merged**
