### PR TITLE
bugfix: override renderReadable() where missing

### PR DESCRIPTION
**Pull request by pavel-nedvedicky**
To get correct representation of expressions as string, renderReadable() must be overriden for concept.
Implement this method for 3 concepts.

### CODE REVIEW

**Comment by lhartl** [comment]
The build is not running green yet, so we dont consider this PR ready for review. Since the build seems to have hung up, please push a no-op commit (e.g. add an empty line somewhere). When the build is running through, we can review the PR.

**Review by wsafonov — CHANGES_REQUESTED** [review]
Thanks for the contribution! Just one minor change request to make the code cleaner: in `AbstractMinMaxExpression.renderReadable()` there is no need to convert to list. You can also use join operation for the sequence of strings with a custom delimiter. This gives not only consistent code style, but more important avoids list object creation (which can cause some unwanted performance losses in scenarios with large number of method calls).

**Comment by pavel-nedvedicky** [comment]
@wsafonov thank you for the feedback. Changes implemented, hopefully the build will be triggered now.

**Comment by pavel-nedvedicky** [comment]
@lhartl is there something I can do to trigger the build? Seems it won't run again. 
Could it be caused by PR from forked repo?

**Comment by lhartl** [comment]
yes, this is due to the fork. Is there a reason why you prefer to use the fork? In your case I would not recommend to fork because your project uses the regular iets3.opensource as a dependency. 
If it's ok for you, please use a regular branch.

**Comment by pavel-nedvedicky** [comment]
Closing due to not running build.

**Pull request closed without merging**
