### PR TITLE
Implement missing base types

### PR DESCRIPTION
**Pull request by alexanderpann**
I am not sure about the TaggedType. It also has a base type, but there is a type system check that fails when the method is implemented.

### CODE REVIEW

**Comment by lhartl** [comment]
which typesystem check fails when the method is implemented for tagged types?

**Comment by alexanderpann** [comment]
https://build.mbeddr.com/buildConfiguration/Iets3_BuildOrgIets3core/333366?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildTestsSection=true

**Review by arimer — CHANGES_REQUESTED** [review]
I just had a closer look to the problem. Chaning the behaviour impl. of `TaggedType.baseType()` would change the semantic of what a base type of TaggedType should be. **Before** the change the baseType of a TaggedType was the TaggedType itself. **After** the change we delegate to its child `TaggedType.baseType`. To be honest, I am not 100% sure what is the right impl. here. In case we change it, our internal API would calculate a different expected base type for TaggedType and might break on runtime, because it is expecting an other type.

This is excactly the problem for the breaking test, because the test is relying on the fact that:
[ur.ancestor<concept = TaggedType>.baseType:TypedefType.baseType()](http://127.0.0.1:63320/node?ref=r%3Abf3cd5a0-eefc-4fd9-b3a6-b57643c9d80c%28org.iets3.core.expr.typetags.units.typesystem%29%2F4020487592981850840)is delgating to [TypeDef.baseType()](http://127.0.0.1:63320/node?ref=r%3Acfd59c48-ecc8-4b0c-8ae8-6d876c46ebbb%28org.iets3.core.expr.toplevel.behavior%29%2F1103723565285356950) which again invokes the (now changed) `baseType()` implementation on an instanec of TaggedType, resulting in a different returned value.

I would argue, in case the want to override the default implemention of [Type.baseType()](http://127.0.0.1:63320/node?ref=r%3A83e946de-2a7f-4a4c-b3c9-4f671aa7f2db%28org.iets3.core.expr.base.behavior%29%2F1103723565285353914) of any subconcepts of `Type`, we must ensure that the calculated runtime type is correct. This would mean, that code which expects the (old) default impl. of `baseType()` would need to be updated to handle the (new) different return type.

I dont think we can merge this PR withouth the required changes sketched above.

**Comment by alexanderpann** [comment]
I am closing this PR in favor of #723 and I'll keep the `TaggedType` as it is.

**Pull request closed without merging**
