### PR TITLE
Implement an ncopies operation for tuples to ease initialization

### PR DESCRIPTION
**Pull request by alexanderpann**
The use case is long initializers with the same values such as initializing a tuple with zeros.                                                                                                      

Example: `assert [1, 2].nTimes(3) equals [1, 2, 1, 2, 1, 2]`

### CODE REVIEW

**Review by arimer — CHANGES_REQUESTED** [review]
In general I like your idea, however there is still a limitation we should address before merging:

- at the moment the  **NCopiesOp** contains an [expression](http://127.0.0.1:63320/node?ref=r%3A66e07cb4-a4b0-4bf3-a36d-5e9ed1ff1bd3%28org.iets3.core.expr.base.structure%29%2F2403760773179493048) which allows users to define  arbitrary expressions. However it looks like only number literals are supported at the time being. 
- Creating a `[1].nTimes(3 + 1)` results in a warning and throws an exception during evaluation 
grafik
- It throws an `EvaluatorMissingException`
- in case we only support number literals we should we should add some constraints to only allow that kind of expression.

Here the stacktrace: 
[com.mbeddr.mpsutil.interpreter.rt.Evaluate.txt](https://github.com/user-attachments/files/16069447/com.mbeddr.mpsutil.interpreter.rt.Evaluate.txt)

**Comment by alexanderpann** [comment]
I've changed the implementation to use an integer property but this issue bothers me and I saw it before. In your case, we try to invoke the interpreter from an inference rule but MPS can't calculate the type for 3+1 which is necessary to check the interpreter constraints. As a result, the interpreter rule for the plus expression is not applied. It works [here](http://127.0.0.1:63320/node?ref=r%3A6081d9c2-0e60-4ebc-a451-4434c25f85c8%28org.iets3.core.expr.repl.typesystem%29%2F5949014564335455787&project=org.iets3.opensource) for the Cell concept because it is a checking rule though. It also doesn't work for replacement rules.
We really need to find a workaround in the future to make that code work.

**Comment by arimer** [comment]
I am just wondering if it would help to have a secod `when concrete` block that forces MPS to wait for the type calculation of the expression 🤔

**Comment by alexanderpann** [comment]
Thanks, that works indeed.

**Review by arimer — APPROVED** [review]
Looks better 👍🏼

**Pull request merged**
