### PR TITLE
IntHelper.equals now correctly deals with the combination of 0.0,-0.0, 0 and -0

### PR DESCRIPTION
**Pull request by alexanderpann**
This PR fixes https://github.com/IETS3/iets3.opensource/issues/761.

### CODE REVIEW

**Comment by alexanderpann** [comment]
I've reverted the accidental change in the intentions model. MPS shows me that the files are identical.

**Comment by markusvoelter** [comment]
You wrote tests of course, but shouldn't the equals test use the == 0 test instead of 
   new BigDecimal(l).compareTo(new BigDecimal(r)) >= 0

**Comment by alexanderpann** [comment]
Yes, that was a copy-paste error. I fixed it. Scary that despite so many tests, I still missed such an easy case.

**Comment by markusvoelter** [comment]
Yes, indeed.

**Review by markusvoelter — APPROVED** [review]

**Pull request merged**
