### PR TITLE
Proper support of collections in test asserts

### PR DESCRIPTION
**Pull request by wsafonov**
This PR includes support of handling collections with numbers when executing asserts in test suites. Before EqualsTestOp in the assert only took care of comparing BigInteger and BigDecimal objects by wrapping BigInteger into BigDecimal and using corresponding `compareTo()` method in BigDecimal (instead of `equals()` method which could not handle BigInteger/BigDecimal). However in case of collections it simply delegated to the `equals()` method and therefore never correctly handled numbers in the collections, which could be semantically equal, but not according to the strict equals() implementation. For example:

```
val fraction = list(1 / 4)                                                                               
test case divide [fail] {                                                                                
  assert fraction equals list(0.25) [1 ms] [error] Test Failed. Expected: [0.25], but was: [0.2500000000]
}                                                                                                        
```                                                                                               
This fails because number precision after division doesn't equal precision of the number literal, even if the number is the same. Comparing these two parts w/o a list would work, because we would then apply custom equals logic from above, which ignores different precisions.

To handle this correctly EqualsHelper has been extended to compare collections (Lists and Sets) and apply custom equals logic to its elements.

This PR also includes another small extension: `IContextTypedOp` interface, which is an extension of `IDotTarget` that automatically derives its type from the context expression in `DotExpression`

### CODE REVIEW

**Comment by markusvoelter** [comment]
... from a dependency perspective this works? Does the EqualsHelper see the Lists and Sets?

**Comment by wsafonov** [comment]
> ... from a dependency perspective this works? Does the EqualsHelper see the Lists and Sets?

Don't quite understand, what do you mean. Why wouldn't it be able to see List and Set? Those are just usual java.util classes, no big difference to BigInteger/BigDecimal.

**Comment by markusvoelter** [comment]
It might need access to the concepts ... but if not, good.

**Comment by wsafonov** [comment]
> It might need access to the concepts ... but if not, good.

Ok, maybe for some other comparision logic. In this case I stay on the level of standard List/Set abstractions and only implement comparision logic according to their corresponding contracts.

**Pull request merged**
