### PR TITLE
Provide Env for TaskRunPhase (#1152)

### PR DESCRIPTION
**Pull request by dbinkele**
solves #1152

### CODE REVIEW

**Review by kbirken — CHANGES_REQUESTED** [review]
Looks good, but: in several places in the productive code and in tests you introduced the following code (with varying inner argument, the one providing the repository):

image

It would be nice to have some static helper method which can be used at all these places.

**Comment by dbinkele** [comment]
> Thanks for refactoring the duplicate code places. But: In the new tests there are also three more of them... example [node URL](http://127.0.0.1:63320/node?ref=r%3A323df21b-bcb0-4525-967d-a41bb2c3fcb8%28test.org.iets3.analysis.base.async%40tests%29%2F682624529721994484)

The mentioned method has a 'Repository' as a parameter.  The methods introduced in the last step has a 'node' as a parameter from which it takes the model and then the repository. In the tests we take the repository of the project. Thus, there is no way of substitute one for another.......?!

**Comment by kbirken** [comment]
> @kbirken The mentioned method has a 'Repository' as a parameter. The methods introduced in the last step has a 'node' as a parameter from which it takes the model and then the repository. In the tests we take the repository of the project. Thus, there is no way of substitute one for another.......?!

During my brief inspection the methods looked quite similar (only the parameter differed), so I thought it were feasible to abstract out a common part. But if not possible, no problem, I'll approve.

**Review by kbirken — APPROVED** [review]
LGTM

**Pull request merged**
