### PR TITLE
Run SolverTask on low-prio thread (#1002)

### PR DESCRIPTION
**Pull request by dbinkele**
implements #1022

### CODE REVIEW

**Comment by dbinkele** [comment]
@kbirken it seems with this PR also this one is fixed: #778

**Review by kbirken — APPROVED** [review]
Tested running solver check on IVAA in variability, against https://github.com/IETS3/iets3.core/pull/1336 -> works.

Cannot test the positive impact of these changes on performance right now. But we can do this in customer project after the integration chain.

**Review by kbirken — COMMENTED** [review]
Just found a problem with iets3.core and checking Feature Models, has to be solved first.

**Review by kbirken — CHANGES_REQUESTED** [review]
Problems occurring in checking of feature models in IETS3.core have to be solved first.

**Comment by arimer** [comment]
@dbinkele , @kbirken why is this PR targeting the datev staging branch?

**Comment by kbirken** [comment]
> @dbinkele , @kbirken why is this PR targeting the datev staging branch?

It probably targeted `maintenance/mps20222` before, and was retargeted to some arbitrary branch when the previous one was deleted by accident. Just guessing….

**Comment by arimer** [comment]
I changed the target branch to the restored one: maintenance/mps20222

**Pull request closed without merging**
