### PR TITLE
Enumerations can have an order

### PR DESCRIPTION
**Pull request by mgronover**
This PR addresses issue #750 

It is fully compatible with previous versions (no breaking changes).
No migration is needed.

### CODE REVIEW

**Comment by arimer** [comment]
I fixed 1,2,4,6 and and 7. Hope that is ok for you :)

**Comment by arimer** [comment]
@mgronover is this PR ready for a second round of review?

**Comment by mgronover** [comment]
Not yet, there are some test cases to do.

**Comment by mgronover** [comment]
Thanks for fixing 1,2,4,6 and and 7! 

add 3)
We need it to call compareTo on the object of the value associated with the enum literal.

add 5)
I saw it in the code: you also fixed item 5 of your list above. Thanks!

I added some test for enum values that implement canBeSorted() retruning "true". Additionally I introduced an assertion to stay safe in the future. Ensuring the interface Comparable is implemented for these classes.

**Review by arimer — APPROVED** [review]
The implemenation looks finally good :) 

Please a proper PR description and sketch really short what was done on a very high level.

**Pull request merged**
