### PR TITLE
Remove MetaUnit and refactor unit comparisons

### PR DESCRIPTION
**Pull request by HeikoBecker**
If the same unit is defined in different packages, this now leads to an error. The error shows the package in which they are not aligned as well as the root.

### CODE REVIEW

**Comment by HeikoBecker** [comment]
PR is currently blocked by #705 which adds a changelog to the base branch. The changes in this PR need to be documented there.

**Review by alexanderpann — CHANGES_REQUESTED** [review]
Please add a test that tests this new behavior.

**Review by alexanderpann — CHANGES_REQUESTED** [review]
The rest of the changes look fine. 

- For me, it is important that now the scenario `val a : number<m> = 10 m` also throws an error when the units do not match. This should be another test case.

- You forgot to change the format of the error message as discussed.

**Comment by HeikoBecker** [comment]
The recommended changes should be addressed now.
In the last commit I also fixed a test that broke because references to units now are non-transparent. The used `cm` unit pointed to the wrong file and thus the conversion could not be found anymore.

**Comment by alexanderpann** [comment]
There shouldn't be too many unit definition that we need the model name. How about just \[root name\].\[unit name\]? The full information doesn't look good in the editor and also not in the type preview.

**Comment by HeikoBecker** [comment]
Agreed. I have adapted the strings accordingly.

**Review by alexanderpann — DISMISSED** [review]

**Comment by HeikoBecker** [comment]
@alexanderpann The last commit only documents the changes in this PR in the changelog.

**Review by alexanderpann — APPROVED** [review]

**Pull request merged**
