### PR TITLE
Make collectiontype implement IComplexTypeSupportsEquals (#659)

### PR DESCRIPTION
**Pull request by HeikoBecker**
This fixes a bug in the typesystem where equalitites of collections were not typechecked correctly.

### CODE REVIEW

**Comment by HeikoBecker** [comment]
The last commits have extended the new functionality for collections. There was some breakage with the test, as the new support for equality typing on collections made some cases that would previously fail in the semantics fail in the type checking. I have updated the tests accordingly.

**Review by arimer — CHANGES_REQUESTED** [review]
The impl. of _isComparableTo()_ looks fine. However, I think your [comment](http://127.0.0.1:63320/node?ref=r%3A2c0153cb-f6d9-49f3-b0fe-e4f726698ef0%28org.iets3.core.expr.collections.behavior%29%2F4454357034015195699) is missleading:

> // We want to allow e.g. sets to be comparable but not lists with sets
 
According to the impl. you could still compare two lists of basetype set with each other and would have a valid result. For example:  `list<set<boolean>>.isComparableTo(list<set<number>>)` would result in true, which makes sense.

I also think it would not harm to have setup some tests checking the new functionality before mergin this PR.

**Comment by HeikoBecker** [comment]
> The impl. of _isComparableTo()_ looks fine. However, I think your [comment](http://127.0.0.1:63320/node?ref=r%3A2c0153cb-f6d9-49f3-b0fe-e4f726698ef0%28org.iets3.core.expr.collections.behavior%29%2F4454357034015195699) is missleading:
> 
> > // We want to allow e.g. sets to be comparable but not lists with sets
> 
I have changed the comment to better reflect the actual implementation
 
> I also think it would not harm to have setup some tests checking the new functionality before merging this PR.

Indeed, the latest commit added some more tests.

**Review by arimer — DISMISSED** [review]
Thanks for the changes 👍🏼 

The test case is also nice.

Just a minor remark here: In case you want to make sure that a certain case is error free (like [here](http://127.0.0.1:63320/node?ref=r%3A75f6a9e9-cf21-495f-b1aa-7fd992d0d7d0%28test.ts.expr.os.m1%40tests%29%2F1986909083020056108)) you could explicitly ask MPS to do this via [CheckNodeForErrorMessagesOperation](http://127.0.0.1:63320/node?ref=r%3A00000000-0000-4000-0000-011c89590388%28jetbrains.mps.lang.test.structure%29%2F1215607067978). 
So you could write a test, where you expect a case to be error free like this: 

grafik

**Pull request merged**
