### PR TITLE
Migrate to MPS 2022.3

### PR DESCRIPTION
**Pull request by alexanderpann**
- The style of the data table header had to be removed because of a compilation issue. Everything else seems to be working.

### CODE REVIEW

**Review by HeikoBecker — APPROVED** [review]
Thank you for working on this! The changes look good to me.

**Comment by svott7** [comment]
Thanks Alexander and Heiko :)

Should we also update the readme file in this PR?

**Comment by HeikoBecker** [comment]
> Thanks Alexander and Heiko :)
> 
> Should we also update the readme file in this PR?

Is there any information that you are missing? As far as I can see the new version has been added to README.md.

**Comment by svott7** [comment]
Ah, excuse me. I was looking on the wrong page. Everything is fine.

**Comment by HeikoBecker** [comment]
> Ah, excuse me. I was looking on the wrong page. Everything is fine.

No worries. Thanks for the feedback!

**Comment by HeikoBecker** [comment]
This PR should be blocked until #746 is merged.

**Pull request merged**
