### PR TITLE
Merge maintenance/mps20211 into maintenance/mps20212

### PR DESCRIPTION
**Pull request by HeikoBecker**
This PR starts a cascading merge to bring the latest features/bugfixes from `maintenance/mps20211` into `master`.

Update (04.05.2023):

A null pointer exception occured in the generators. It was fixed by porting `a89f1c4541b287701f996c14690058620443f6a8` from `datev-loon-staging-20213`. See below for the discussion.

### CODE REVIEW

**Comment by arimer** [comment]
Although we already discussed this issue, I am posting the stacktrace of the NPE I saw during test execution from command line: 

```
 [junit] ERROR: update failed for AnAction(org.iets3.core.expr.plugin.plugin.Generator) with text=KernelF Tests: Generator
    [junit] java.lang.NullPointerException
    [junit]     at org.iets3.core.expr.plugin.plugin.Generator.isSelected(Generator.java:28)
    [junit]     at com.intellij.openapi.actionSystem.ToggleAction.update(ToggleAction.java:72)
    [junit]     at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:130)
    [junit]     at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:144)
    [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:584)
    [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$7(ActionUpdater.java:132)
    [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$9(ActionUpdater.java:187)
    [junit]     at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
    [junit]     at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
    [junit]     at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
    [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$10(ActionUpdater.java:185)
    [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
    [junit]     at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
    [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
    [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
    [junit]     at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    [junit]     at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    [junit]     at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    [junit]     at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    [junit]     at java.base/java.security.AccessController.doPrivileged(Native Method)
    [junit]     at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    [junit]     at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    [junit]     at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
    [junit]     at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
    [junit]     at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
    [junit]     at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
    [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
    [junit]     at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
    [junit]     at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:945)
    [junit]     at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$7(ProgressWindow.java:229)
    [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:820)
    [junit]     at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:225)
    [junit]     at com.intellij.openapi.progress.impl.ProgressRunner.lambda$execFromEDT$6(ProgressRunner.java:311)
    [junit]     at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    [junit]     at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    [junit]     at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    [junit]     at com.intellij.openapi.progress.impl.ProgressRunner.execFromEDT(ProgressRunner.java:308)
    [junit]     at com.intellij.openapi.progress.impl.ProgressRunner.submit(ProgressRunner.java:258)
    [junit]     at com.intellij.openapi.progress.impl.ProgressRunner.submitAndGet(ProgressRunner.java:183)
    [junit]     at com.intellij.openapi.project.impl.ProjectUiFrameAllocator.run(ProjectFrameAllocator.kt:116)
    [junit]     at com.intellij.openapi.project.impl.ProjectManagerExImpl.doOpenAsync(ProjectManagerExImpl.kt:115)
    [junit]     at com.intellij.openapi.project.impl.ProjectManagerExImpl.openProjectAsync(ProjectManagerExImpl.kt:106)
    [junit]     at com.intellij.openapi.project.impl.ProjectManagerExImpl.openProject(ProjectManagerExImpl.kt:73)
    [junit]     at com.intellij.openapi.project.impl.ProjectManagerExImpl.loadAndOpenProject(ProjectManagerExImpl.kt:69)
    [junit]     at jetbrains.mps.tool.environment.IdeaEnvironment$4.run(IdeaEnvironment.java:285)
    [junit]     at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
    [junit]     at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
    [junit]     at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
    [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
    [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:451)
    [junit]     at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
    [junit]     at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    [junit]     at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    [junit]     at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    [junit]     at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    [junit]     at java.base/java.security.AccessController.doPrivileged(Native Method)
    [junit]     at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    [junit]     at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    [junit]     at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
    [junit]     at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
    [junit]     at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
    [junit]     at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
    [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
    [junit]     at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
    [junit]     at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    [junit]     at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    [junit]     at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    [junit]     at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    [junit]     at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    [junit]     at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
    [junit] Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
    [junit] ERROR: update failed for AnAction(org.iets3.core.expr.plugin.plugin.Generator) with text=KernelF Tests: Generator
    [junit] java.lang.NullPointerException
    [junit]     at org.iets3.core.expr.plugin.plugin.Generator.isSelected(Generator.java:28)
    [junit]     at com.intellij.openapi.actionSystem.ToggleAction.update(ToggleAction.java:72)
    [junit]     at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:130)
    [junit]     at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:144)
    [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:584)
    [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$7(ActionUpdater.java:132)
    [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$9(ActionUpdater.java:187)
    [junit]     at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
    [junit]     at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
    [junit]     at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
    [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$10(ActionUpdater.java:185)
    [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
    [junit]     at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
    [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
    [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
    [junit]     at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
    [junit]     at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    [junit]     at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    [junit]     at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    [junit]     at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    [junit]     at java.base/java.security.AccessController.doPrivileged(Native Method)
    [junit]     at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    [junit]     at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    [junit]     at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
    [junit]     at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
    [junit]     at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
    [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
    [junit]     at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
    [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
    [junit]     at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
    [junit]     at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    [junit]     at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    [junit]     at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    [junit]     at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    [junit]     at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    [junit]     at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

In case this is error was introduce during the cascading merge, we should fix it.

**Comment by arimer** [comment]
Locally I can see some broken tests and I can't tell if they can be ignored or not: 

**Broken/Ignored Tests**
grafik

**Amount of tests**
grafik

I have also briefly checked the Team City build and see that there are not broken tests there: 
https://build.mbeddr.com/buildConfiguration/Iets3_BuildOrgIets3core/339043?buildTab=tests

@HeikoBecker , @alexanderpann do I maybe need to configure MPS in any other way to run the tests?

**Comment by alexanderpann** [comment]
TeamCity runs the tests with the generator, they might only work for you locally with the interpreter. I ran into those kinds of problems myself and I would guess that the generation of the test cases fails because the tests can't be generated. I would check the output of the generation and also the generation plans. There are some interesting behaviors of the generator in MPS 2021.2 and 2021.3 that we might not have fixed yet (e.g. extends scopes in generator modules works differently, $CALL$ macro is no longer skipped on null input etc)

**Review by arimer — APPROVED** [review]
The found behaviour (exceptions, same broken tests) is also present on the target branch therefore they are no blockers for the merge. 

Approval for my side 👍🏼

**Comment by HeikoBecker** [comment]
> Although we already discussed this issue, I am posting the stacktrace of the NPE I saw during test execution from command line:
> 
> ```
>  [junit] ERROR: update failed for AnAction(org.iets3.core.expr.plugin.plugin.Generator) with text=KernelF Tests: Generator
>     [junit] java.lang.NullPointerException
>     [junit]     at org.iets3.core.expr.plugin.plugin.Generator.isSelected(Generator.java:28)
>     [junit]     at com.intellij.openapi.actionSystem.ToggleAction.update(ToggleAction.java:72)
>     [junit]     at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:130)
>     [junit]     at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:144)
>     [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:584)
>     [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$7(ActionUpdater.java:132)
>     [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$9(ActionUpdater.java:187)
>     [junit]     at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
>     [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
>     [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
>     [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
>     [junit]     at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
>     [junit]     at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
>     [junit]     at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
>     [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$10(ActionUpdater.java:185)
>     [junit]     at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
>     [junit]     at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
>     [junit]     at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
>  ... (shortened from original message)
> ```
> 
> In case this is error was introduce during the cascading merge, we should fix it.

The error was present in the base branch too. There was a fix in the `datev-loon-staging-20213` branch which I have applied in the latest commit.

**Review by arimer — APPROVED** [review]

**Pull request merged**
